/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import model.MyColor;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Cat;
import services.CatServices;

/**
 *
 * @author ppolo
 */
public class CatsManagement extends javax.swing.JFrame implements Runnable {

    private CatServices cats;
    private DefaultTableModel defaultTableModel;

    /**
     * Creates new form CatManagement
     */
    public CatsManagement() {
        initComponents();
        this.setLocationRelativeTo(null);
        cats = new CatServices();
        defaultTable();
        Thread t1 = new Thread(this);
        t1.start();
        btnShow.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProgramName = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblCatId = new javax.swing.JLabel();
        txtCatId = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblCatName = new javax.swing.JLabel();
        txtCatName = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCat = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnSave = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CatsManagement");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProgramName.setFont(new java.awt.Font("Snap ITC", 2, 32)); // NOI18N
        lblProgramName.setForeground(new java.awt.Color(0, 51, 51));
        lblProgramName.setText("CAT MANAGEMENT");
        getContentPane().add(lblProgramName, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 25, -1, -1));

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTime.setText("10:10");
        lblTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTimeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTimeMouseExited(evt);
            }
        });
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 477, 120, -1));

        lblCatId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCatId.setForeground(new java.awt.Color(255, 255, 255));
        lblCatId.setText("CatId:");
        getContentPane().add(lblCatId, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 105, -1, -1));

        txtCatId.setForeground(new java.awt.Color(51, 51, 51));
        txtCatId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCatIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCatIdFocusLost(evt);
            }
        });
        getContentPane().add(txtCatId, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 102, 80, -1));

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantity.setText("Quantity:");
        getContentPane().add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 155, -1, -1));

        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantityFocusLost(evt);
            }
        });
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 152, 80, -1));

        lblWeight.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWeight.setForeground(new java.awt.Color(255, 255, 255));
        lblWeight.setText("Weight:");
        getContentPane().add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 203, -1, -1));

        txtWeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtWeightFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWeightFocusLost(evt);
            }
        });
        getContentPane().add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 200, 80, -1));

        lblCatName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCatName.setForeground(new java.awt.Color(255, 255, 255));
        lblCatName.setText("Cat name:");
        getContentPane().add(lblCatName, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 105, -1, -1));

        txtCatName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCatNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCatNameFocusLost(evt);
            }
        });
        getContentPane().add(txtCatName, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 102, 258, -1));

        lblColor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblColor.setForeground(new java.awt.Color(255, 255, 255));
        lblColor.setText("Color:");
        getContentPane().add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 155, -1, -1));

        txtColor.setForeground(new java.awt.Color(0, 51, 255));
        txtColor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtColorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtColorFocusLost(evt);
            }
        });
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 152, 258, -1));

        txtPrice.setForeground(new java.awt.Color(51, 51, 51));
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriceFocusLost(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 200, 258, -1));

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice.setText("Price:");
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 203, -1, -1));

        tblCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 308, 544, 110));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 456, 602, 10));

        btnSave.setForeground(new java.awt.Color(51, 51, 51));
        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 265, 60, -1));

        btnShow.setText("Show");
        btnShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnShowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnShowMouseExited(evt);
            }
        });
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        getContentPane().add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 265, 70, -1));

        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 265, 63, -1));

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 265, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 265, 78, -1));

        btnExit.setForeground(new java.awt.Color(51, 51, 51));
        btnExit.setIcon(new javax.swing.ImageIcon("D:\\FPTPolytechnic\\MOB1023\\Assignment\\src\\btnIcon\\exit.gif")); // NOI18N
        btnExit.setText("  Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        lblBackGround.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBackGround.setIcon(new javax.swing.ImageIcon("D:\\FPTPolytechnic\\MOB1023\\Assignment\\src\\background.gif")); // NOI18N
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void defaultTable() {
        defaultTableModel = (DefaultTableModel) tblCat.getModel();
        defaultTableModel.setColumnCount(0);
        defaultTableModel.addColumn("Cat Id");
        defaultTableModel.addColumn("Cat name");
        defaultTableModel.addColumn("Quantity");
        defaultTableModel.addColumn("Color");
        defaultTableModel.addColumn("Weight");
        defaultTableModel.addColumn("Price");
        defaultTableModel.setRowCount(0);
    }

    private void fillTable() {
        defaultTableModel.setRowCount(0);
        for (Cat cat : cats.getAll()) {
            defaultTableModel.addRow(new Object[]{cat.getCatId(), cat.getCatName(), cat.getQuantity(), cat.getMyColor(), cat.getWeight() + "KG ", cat.getPrice() + " VNĐ"});
        }

    }

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        try {
            // TODO add your handling code here:
            btnSave.setEnabled(true);
            cats.readFile();
            fillTable();

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi đọc file!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnShowActionPerformed

    private void setColor(JTextField txt, JLabel lbl) {
        Font font1 = new Font("Segoe UI", Font.BOLD, 15);
        Color color1 = new Color(0, 51, 255);

        txt.setForeground(color1);
        lbl.setFont(font1);
        lbl.setForeground(color1);
    }

    private void resetColor(JTextField txt, JLabel lbl) {
        Font font2 = new Font("Segoe UI", Font.BOLD, 12);
        Color color2 = new Color(255, 255, 255);
        Color color3 = new Color(51, 51, 51);

        txt.setForeground(color3);
        lbl.setFont(font2);
        lbl.setForeground(color2);

    }

    private void txtCatIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCatIdFocusGained
        // TODO add your handling code here:
        setColor(txtCatId, lblCatId);
    }//GEN-LAST:event_txtCatIdFocusGained

    private void txtCatIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCatIdFocusLost
        // TODO add your handling code here:
        resetColor(txtCatId, lblCatId);
    }//GEN-LAST:event_txtCatIdFocusLost

    private void txtQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusGained
        // TODO add your handling code here:
        setColor(txtQuantity, lblQuantity);
    }//GEN-LAST:event_txtQuantityFocusGained

    private void txtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusLost
        // TODO add your handling code here:
        resetColor(txtQuantity, lblQuantity);
    }//GEN-LAST:event_txtQuantityFocusLost

    private void txtWeightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWeightFocusGained
        // TODO add your handling code here:
        setColor(txtWeight, lblWeight);
    }//GEN-LAST:event_txtWeightFocusGained

    private void txtWeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWeightFocusLost
        // TODO add your handling code here:
        resetColor(txtWeight, lblWeight);
    }//GEN-LAST:event_txtWeightFocusLost

    private void txtCatNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCatNameFocusGained
        // TODO add your handling code here:
        setColor(txtCatName, lblCatName);
    }//GEN-LAST:event_txtCatNameFocusGained

    private void txtCatNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCatNameFocusLost
        // TODO add your handling code here:
        resetColor(txtCatName, lblCatName);
    }//GEN-LAST:event_txtCatNameFocusLost

    private void txtColorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorFocusGained
        // TODO add your handling code here:
        setColor(txtColor, lblColor);
    }//GEN-LAST:event_txtColorFocusGained

    private void txtColorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorFocusLost
        // TODO add your handling code here:
        resetColor(txtColor, lblColor);
    }//GEN-LAST:event_txtColorFocusLost

    private void txtPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusGained
        // TODO add your handling code here:
        setColor(txtPrice, lblPrice);
        lblPrice.setForeground(new Color(102, 255, 0));
    }//GEN-LAST:event_txtPriceFocusGained

    private void txtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusLost
        // TODO add your handling code here:
        resetColor(txtPrice, lblPrice);
    }//GEN-LAST:event_txtPriceFocusLost

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            // TODO add your handling code here:
            cats.saveFile(cats.getAll());
            JOptionPane.showMessageDialog(this, "<html><font face='Calibri' size='15' color='green'>Lưu thành công!", "Successfull", 1, new ImageIcon("D:\\FPTPolytechnic\\MOB1023\\Assignment\\src\\btnIcon\\saveicon.gif"));
            btnSave.setEnabled(false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi không thể lưu file!", "Error", 0);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private String replaceDeviceAAdd(String str) {
        char device = '-';
        int count = 0;
        for (int i = 0; i < str.length(); i++) {
            if (str.charAt(i) == device) {
                count++;
            }
        }

        if (count % 2 == 0) {
            str = str.replaceAll("\\+", "").replaceAll("-", "").replaceAll(" ", "");
        } else {
            str = "-" + str.replaceAll(" ", "").replaceAll("\\+", "").replaceAll("-", "");
        }
        return str;
    }

    private String checkId() {
        String str = "";
        String catIdStr = txtCatId.getText().trim();

        if (catIdStr.equals("") || catIdStr.matches("\\s+")) {
            str += "Cat id is empty!\n";
        } else if (!catIdStr.matches("((((\\+)+(\\s+)?)?((-)+(\\s+)?)?((\\+)+(\\s+)?)?((-)+(\\s+)?)?)+)?\\d+")) {
            str += "Cat id không đúng định dạng!\n";
        } else if (Integer.parseInt(replaceDeviceAAdd(catIdStr)) <= 0) {
            str += "Cat id không được <= 0!\n";
        }

        return str;
    }

    private boolean checkChungId(int id) {
        for (Cat cat : cats.getAll()) {
            if (cat.getCatId() == id) {
                return true;
            }
        }
        return false;
    }

    private String checkJTextField() {
        String str = checkId();
        String catNameStr = txtCatName.getText().trim();
        String catColorStr = txtColor.getText().trim();
        String catPriceStr = txtPrice.getText().trim();
        String catQuantityStr = txtQuantity.getText().trim();
        String catWeightStr = txtWeight.getText().trim();

        if (catNameStr.equals("") || catNameStr.matches("\\s+")) {
            str += "Cat name is empty!\n";
        }

        MyColor[] colors = MyColor.values();
        int checkColor = 0;
        for (MyColor color : colors) {
            if (catColorStr.equalsIgnoreCase(color + "")) {
                checkColor = 1;
                break;
            }
        }
        if (checkColor == 0) {
            str += "Cat color không đúng định dạng!\n";
        }

        if (!catPriceStr.matches("((((\\+)+(\\s+)?)?((-)+(\\s+)?)?((\\+)+(\\s+)?)?((-)+(\\s+)?)?)+)?\\d+(.\\d+)?")) {
            str += "Price không đúng định dạng!\n";
        } else if (BigDecimal.valueOf(Double.valueOf(replaceDeviceAAdd(catPriceStr))).compareTo(BigDecimal.valueOf(0)) < 0) {
            str += "Price không được < 0!\n";
        }

        if (!catQuantityStr.matches("((((\\+)+(\\s+)?)?((-)+(\\s+)?)?((\\+)+(\\s+)?)?((-)+(\\s+)?)?)+)?\\d+")) {
            str += "Quantity phải là số nguyên!\n";
        } else if (Integer.parseInt(replaceDeviceAAdd(catQuantityStr)) < 0) {
            str += "Quantity phải là số > 0!\n";
        }

        if (!catWeightStr.matches("((((\\+)+(\\s+)?)?((-)+(\\s+)?)?((\\+)+(\\s+)?)?((-)+(\\s+)?)?)+)?\\d+(.\\d+)?")) {
            str += "Weight không đúng định dạng!\n";
        } else if (Float.parseFloat(replaceDeviceAAdd(catWeightStr)) < 0) {
            str += "Weight phải là số thực > 0!\n";
        }

        return str;
    }

    public Cat selectInfCat() {
        Integer catId = Integer.parseInt(replaceDeviceAAdd(txtCatId.getText().trim()));
        String catName = txtCatName.getText().trim();
        BigDecimal price = BigDecimal.valueOf(Double.parseDouble(replaceDeviceAAdd(txtPrice.getText().trim())));
        Integer quantity = Integer.parseInt(replaceDeviceAAdd(txtQuantity.getText().trim()));
        MyColor color = MyColor.valueOf(txtColor.getText().trim().toUpperCase());
        Float weight = Float.parseFloat(txtWeight.getText().trim());

        return new Cat(catId, catName, price, quantity, color, weight);
    }

    private void clearAllField() {
        txtCatId.setText("");
        txtCatName.setText("");
        txtColor.setText("");
        txtPrice.setText("");
        txtQuantity.setText("");
        txtWeight.setText("");
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String temp = checkJTextField();
        String temp2 = "";
        if (temp.equals("")) {
            if (checkChungId(Integer.parseInt(txtCatId.getText()))) {
                temp2 += "Tồn tại id: " + txtCatId.getText() + "!";
                JOptionPane.showMessageDialog(this, temp2, "Error", 2);
            } else {
                cats.addCat(selectInfCat());
                fillTable();
                clearAllField();
                JOptionPane.showMessageDialog(this, "<html><font face='Calibri' size='15' color='green'>Thêm thành công!", "Succesfull", 1, new ImageIcon("D:\\FPTPolytechnic\\MOB1023\\Assignment\\src\\btnIcon\\success.gif"));
                btnSave.setEnabled(true);

            }

        } else {
            JOptionPane.showMessageDialog(this, temp, "Error", 2);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCatMouseClicked
        // TODO add your handling code here:
        int row = tblCat.getSelectedRow();
        txtCatId.setText(tblCat.getValueAt(row, 0) + "");
        txtCatName.setText(tblCat.getValueAt(row, 1) + "");
        txtQuantity.setText(tblCat.getValueAt(row, 2) + "");
        txtColor.setText(tblCat.getValueAt(row, 3) + "");
        txtWeight.setText((tblCat.getValueAt(row, 4) + "").replaceAll("KG", ""));
        txtPrice.setText((tblCat.getValueAt(row, 5) + "").replaceAll(" VNĐ", ""));
    }//GEN-LAST:event_tblCatMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id = checkJTextField();
        if (id.equals("")) {
            int catId = Integer.parseInt(txtCatId.getText().trim());
            if (cats.findCat(catId) != -1) {
                if (JOptionPane.showConfirmDialog(this, "Bạn có muốn update không?") == JOptionPane.OK_OPTION) {

                    cats.updateCat(selectInfCat());
                    JOptionPane.showMessageDialog(this, "<html><font face='Calibri' size='15' color='green'>Sửa thành công!", "Succesfull", 1, new ImageIcon("D:\\FPTPolytechnic\\MOB1023\\Assignment\\src\\btnIcon\\success.gif"));
                    fillTable();
                    btnSave.setEnabled(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy!", "Error", 2);

            }
        } else {
            JOptionPane.showMessageDialog(this, id, "Error", 2);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String temp = checkId();
        if (temp.equals("")) {
            int catId = Integer.parseInt(txtCatId.getText().trim());
            if (cats.findCat(catId) != -1) {
                if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?") == JOptionPane.OK_OPTION) {

                    cats.deleteCat(catId);
                    fillTable();
                    btnSave.setEnabled(true);
                    JOptionPane.showMessageDialog(this, "<html><font face='Calibri' size='15' color='red'>Xóa thành công!", "Succesfull", 1, new ImageIcon("D:\\FPTPolytechnic\\MOB1023\\Assignment\\src\\btnIcon\\deleteCat.gif"));

                }
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy!", "Error", 2);

            }
        } else {
            JOptionPane.showMessageDialog(this, temp, "Error", 2);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void setColorButton(JButton button) {
        Color color1 = new Color(51, 255, 255);//Xanh ngọc 
        Color color2 = new Color(255, 102, 0);//Cam
        Font font = new Font("Segoe UI", Font.BOLD, 13);

        button.setFont(font);
        button.setBackground(color1);
        button.setForeground(color2);
    }

    private void resetColorButton(JButton button) {
        Color color1 = new Color(240, 240, 240);
        Color color2 = new Color(51, 51, 51);
        Font font = new Font("Segoe UI", Font.PLAIN, 12);

        button.setFont(font);
        button.setBackground(color1);
        button.setForeground(color2);
    }

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        // TODO add your handling code here:
        setColorButton(btnSave);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        // TODO add your handling code here:
        resetColorButton(btnSave);
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnShowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMouseEntered
        // TODO add your handling code here:
        setColorButton(btnShow);
    }//GEN-LAST:event_btnShowMouseEntered

    private void btnShowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMouseExited
        // TODO add your handling code here:
        resetColorButton(btnShow);
    }//GEN-LAST:event_btnShowMouseExited

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        // TODO add your handling code here:
        setColorButton(btnAdd);
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        // TODO add your handling code here:
        resetColorButton(btnAdd);
    }//GEN-LAST:event_btnAddMouseExited

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        // TODO add your handling code here:
        setColorButton(btnUpdate);
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        // TODO add your handling code here:
        resetColorButton(btnUpdate);
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        // TODO add your handling code here:
        setColorButton(btnDelete);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        // TODO add your handling code here:
        resetColorButton(btnDelete);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void lblTimeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTimeMouseEntered
        // TODO add your handling code here:
        lblTime.setFont(new Font("Segoe UI", Font.BOLD, 18));
    }//GEN-LAST:event_lblTimeMouseEntered

    private void lblTimeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTimeMouseExited
        // TODO add your handling code here:
        lblTime.setFont(new Font("Segoe UI", Font.BOLD, 12));
    }//GEN-LAST:event_lblTimeMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Confirm", 1) == 0)
            System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        resetColorButton(btnExit);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btnExit.setBackground(new Color(255, 51, 51));
        btnExit.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnExitMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatsManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatsManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatsManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatsManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CatsManagement catsManagement = new CatsManagement();
                catsManagement.setVisible(true);
                catsManagement.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                catsManagement.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        if (btnSave.isEnabled()) {
                            int exit = JOptionPane.showConfirmDialog(catsManagement, "Bạn muốn lưu file không?");
                            if (exit == JOptionPane.OK_OPTION) {
                                btnSave.doClick();
                                System.exit(0);
                            } else if (exit == JOptionPane.NO_OPTION) {
                                System.exit(0);
                            }
                        } else {
                            System.exit(0);
                        }

                    }
                });
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private static javax.swing.JButton btnExit;
    private static javax.swing.JButton btnSave;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblCatId;
    private javax.swing.JLabel lblCatName;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProgramName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTable tblCat;
    private javax.swing.JTextField txtCatId;
    private javax.swing.JTextField txtCatName;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {

        while (true) {
            Date now = new Date();
            SimpleDateFormat myFormatDate = new SimpleDateFormat("hh:mm:ss a");
            String time = myFormatDate.format(now);
            lblTime.setText(time);
        }
    }
}
